[package]
name = "payos-db"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
payos-core.workspace = true
payos-domain.workspace = true
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
uuid.workspace = true

[lints]
workspace = true
